### ISSUE TITLE
Sequin RNA data

### ISSUE THREAD

**Issue by lingminhao** [XueyiDong/LongReadBenchmark#3]
![image](https://github.com/user-attachments/assets/9bc9f91a-486d-46d1-9457-f09e12b329d9)
Hi @XueyiDong, I am currently using the sequin data, and was investigating the metadata. What does the counts under MIX_A (or MIX_B) mean, and their relationship with the length ?

**Comment by XueyiDong** [comment]
Hi @lingminhao ,

Thank you for using the data! The sequins are artificially designed RNA standards pre-mixed into two groups with different abundances. The counts under MIX_A and MIX_B are the designed abundance of the transcripts (ground truth). They should have no relationship with the length.

I hope my explanation makes sense.

Best regards,
Xueyi
