### ISSUE TITLE
sequin data obtain

### ISSUE THREAD

**Issue by tauChange** [XueyiDong/LongReadBenchmark#4]
![image](https://github.com/user-attachments/assets/abfbbb45-fef8-4ccd-84f6-f27e43044db0)
Hi @XueyiDong ,

 I would like to use the sequin data, but I am unable to access it through the link provided in the paper. Where can I obtain this data?

**Comment by XueyiDong** [comment]
Hi @tauChange ,

Thank you for your interest in using our data! I have uploaded the sequin annotation here: [https://github.com/XueyiDong/LongReadRNA/tree/master/sequins/annotations](https://github.com/XueyiDong/LongReadRNA/tree/master/sequins/annotations).

Best wishes,
Xueyi
